[package]
name = "dust-vox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot_vox = { git = "https://github.com/dust-engine/dot_vox.git" }
dust-render = { path = "../render" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
bevy_scene = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f", default-features=false, features=["serialize"] }
bevy_asset = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "e9312254d8906e9f491c4f3761659df0d179687f" }
rhyolite = { path = "../../../rhyolite/core" }
rhyolite-bevy = { path = "../../../rhyolite/bevy" }
dust_vdb = { path = "../vdb" }
glam = "0.23.0"
anyhow = "*"
rayon = "1.7"
