[package]
name = "dust-vox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot_vox = { git = "https://github.com/dust-engine/dot_vox.git" }
dust-render = { path = "../render" }
bevy_app = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
bevy_ecs = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
bevy_scene = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a", default-features=false, features=["serialize"] }
bevy_asset = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
bevy_reflect = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
bevy_hierarchy = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
bevy_transform = { git = "https://github.com/Neo-Zhixing/bevy.git", rev = "08f898b8005f8549cdbe4225716442480354d93a" }
rhyolite = { path = "../../../rhyolite/core" }
rhyolite-bevy = { path = "../../../rhyolite/bevy" }
dust_vdb = { path = "../vdb" }
glam = "0.23.0"
anyhow = "*"
rayon = "1.7"
